// <auto-generated />
namespace SiteEvents.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdeventsandcomments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdeventsandcomments));
        
        string IMigrationMetadata.Id
        {
            get { return "201707251129286_created events and comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
